import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import React from "react";
import Providers from "@/lib/Providers";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/toaster";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Soles Union",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  test,
}: {
  children: React.ReactNode;
  test: any;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          "font-PlexSans"
        )}
      >
        <Providers>
          <NextTopLoader
            color="#000000"
            initialPosition={0.08}
            crawlSpeed={200}
            height={2}
            crawl={true}
            showSpinner={true}
            easing="ease"
            speed={200}
            shadow="0 0 10px #000000,0 0 5px #ffffff"
          />
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
