import { Inter as FontSans, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import React from "react";
import Providers from "@/lib/Providers";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth/next";
import SessionProvider from "@/lib/nextAuth/SessionProvider";

const roboto = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata = {
  title: "Soles Union",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  test,
}: {
  children: React.ReactNode;
  test: any;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased relative",
          roboto.className
        )}
      >
        <SessionProvider session={session}>
          <Providers>
            <NextTopLoader
              color="#000000"
              initialPosition={0.08}
              crawlSpeed={200}
              height={2}
              crawl={true}
              showSpinner={true}
              easing="ease"
              speed={200}
              shadow="0 0 10px #000000,0 0 5px #ffffff"
            />
            {children}
          </Providers>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
